version: "3.8"
services:
 vite_docker:
    image: node:bullseye
    container_name: vite_docker
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./ft_transcendence
        target: /srv/app
    restart: always
    working_dir: /srv/app/Pong
    entrypoint: "npm run dev"
    tty: true